About the Dataset

Context

This dataset focuses on understanding customer behavior in order to improve retention. By analyzing the available customer data, you can design targeted retention programs that reduce churn. (Source: IBM Sample Data Sets)

Content

Every row corresponds to a single customer, and every column describes one of that customer’s attributes, as detailed in the column metadata. The data covers:

Churn status: whether the customer left the company within the last month (the Churn column).
Subscribed services: phone service, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies.
Account details: how long the person has been a customer (tenure), contract type, payment method, paperless billing, monthly charges, and total charges.
Demographics: gender, age range, and whether the customer has a partner or dependents.

In [72]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [73]:
df = pd.read_csv('C:/Users/Amir/Customer_churn-/data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [74]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [75]:
df.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,3186-AJIEK,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

couse of unique in rows  we do some binary incoding

In [76]:
binary_columns = ['gender', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']
df[binary_columns] = df[binary_columns].apply(lambda x: x.map({'Yes': 1, 'No': 0, 'Female': 1, 'Male': 0}))

In [77]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,1,0,1,0,No phone service,DSL,No,...,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,No,DSL,Yes,...,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,No,DSL,Yes,...,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,1,0,0,0,2,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

we do some one_hot_encoding  for unique > 2

In [78]:
multi_cat_cols = ['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

for col in multi_cat_cols:
    dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
    df = pd.concat([df, dummies], axis=1)
    df.drop(col, axis=1, inplace=True)

In [79]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,0,1,0,1,0,1,29.85,29.85,...,False,False,False,False,False,False,False,False,True,False
1,5575-GNVDE,0,0,0,0,34,1,0,56.95,1889.5,...,False,False,False,False,False,True,False,False,False,True
2,3668-QPYBK,0,0,0,0,2,1,1,53.85,108.15,...,False,False,False,False,False,False,False,False,False,True
3,7795-CFOCW,0,0,0,0,45,0,0,42.30,1840.75,...,True,False,False,False,False,True,False,False,False,False
4,9237-HQITU,1,0,0,0,2,1,1,70.70,151.65,...,False,False,False,False,False,False,False,False,True,False

cleaning

In [80]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [81]:
df = df.drop("customerID", axis=1)

In [82]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [83]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,45,0,0,42.30,1840.75,0,...,1,0,0,0,0,1,0,0,0,0
4,1,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,0,1,0

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int64
 6   PaperlessBilling                       7043 non-null   int64
 7   MonthlyCharges                         7043 non-null   float64
 8   TotalCharges                           7032 non-null   float64
 9   Churn                                  7043 non-null   int64
 10  MultipleLines_No phone service         7043 non-null   int64
 11  MultipleLines_Yes                      7043 non-null   int64
 12  InternetService_Fiber optic            7043 non-null   int64
 13  InternetService_No                     7043 non-null   int64
 14  OnlineSecurity_No internet service     7043 non-null   int64
 15  OnlineSecurity_Yes                     7043 non-null   int64
 16  OnlineBackup_No internet service       7043 non-null   int64
 17  OnlineBackup_Yes                       7043 non-null   int64
 18  DeviceProtection_No internet service   7043 non-null   int64
 19  DeviceProtection_Yes                   7043 non-null   int64
 20  TechSupport_No internet service        7043 non-null   int64
 21  TechSupport_Yes                        7043 non-null   int64
 22  StreamingTV_No internet service        7043 non-null   int64
 23  StreamingTV_Yes                        7043 non-null   int64
 24  StreamingMovies_No internet service    7043 non-null   int64
 25  StreamingMovies_Yes                    7043 non-null   int64
 26  Contract_One year                      7043 non-null   int64
 27  Contract_Two year                      7043 non-null   int64
 28  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 29  PaymentMethod_Electronic check         7043 non-null   int64
 30  PaymentMethod_Mailed check             7043 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

In [85]:
df["no_internet_service"] =(
    df["OnlineSecurity_No internet service"] |
    df["OnlineBackup_No internet service"] |
    df["DeviceProtection_No internet service"] |
    df["TechSupport_No internet service"] |
    df["StreamingTV_No internet service"] |
    df["StreamingMovies_No internet service"]
).astype(int)

drop_cols = [col for col in df.columns if "no_internet_service" in col]
df = df.drop(columns=drop_cols)

In [86]:
if "MultipleLines_No phone service" in df.columns:
    df["no_phone_service"] = df["MultipleLines_No phone service"].astype(int)
df = df.drop(columns=["MultipleLines_No phone service"])

In [87]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,no_phone_service
0,1,0,1,0,1,0,1,29.85,29.85,0,...,0,0,0,0,0,0,0,1,0,1
1,0,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,0,0,2,1,1,53.85,108.15,1,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,45,0,0,42.30,1840.75,0,...,0,0,0,0,1,0,0,0,0,1
4,1,0,0,0,2,1,1,70.70,151.65,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,84.80,1990.50,0,...,0,1,0,1,1,0,0,0,1,0
7039,1,0,1,1,72,1,1,103.20,7362.90,0,...,0,1,0,1,1,0,1,0,0,0
7040,1,0,1,1,11,0,1,29.60,346.45,0,...,0,0,0,0,0,0,0,1,0,1
7041,0,1,1,0,4,1,1,74.40,306.60,1,...,0,0,0,0,0,0,0,0,1,0
7042,0,0,0,0,66,1,1,105.65,6844.50,0,...,0,1,0,1,0,1,0,0,0,0

In [88]:
X = df.drop(columns=['Churn'])
bool_cols =X.select_dtypes(include='bool').columns
X[bool_cols] = X[bool_cols].astype(int)

In [89]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import numpy as np

X = X.replace([np.inf , -np.inf] , np.nan)
X = X.dropna()
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif_data = vif_data.sort_values(by="VIF", ascending=False)

print(vif_data)

C:\Users\Amir\AppData\Local\Temp\ipykernel_18144\331431101.py:8: UserWarning: The design matrix is poorly conditioned (condition number=8.19e+18). VIF calculations may be numerically unstable.
  vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared

                                  feature           VIF
5                            PhoneService  1.000800e+15
12     OnlineSecurity_No internet service  1.000800e+15
11                     InternetService_No  1.000800e+15
20        StreamingTV_No internet service  1.000800e+15
16   DeviceProtection_No internet service  1.000800e+15
14       OnlineBackup_No internet service  1.000800e+15
18        TechSupport_No internet service  1.000800e+15
29                       no_phone_service  1.000800e+15
22    StreamingMovies_No internet service  1.000800e+15
7                          MonthlyCharges  8.660896e+02
10            InternetService_Fiber optic  1.485008e+02
23                    StreamingMovies_Yes  2.415639e+01
21                        StreamingTV_Yes  2.408002e+01
8                            TotalCharges  1.081149e+01
4                                  tenure  7.584453e+00
9                       MultipleLines_Yes  7.289761e+00
17                   DeviceProtection_Yes  6.924754e+00
15                       OnlineBackup_Yes  6.796678e+00
19                        TechSupport_Yes  6.476508e+00
13                     OnlineSecurity_Yes  6.338349e+00
25                      Contract_Two year  2.652328e+00
27         PaymentMethod_Electronic check  1.976032e+00
28             PaymentMethod_Mailed check  1.857058e+00
24                      Contract_One year  1.625784e+00
26  PaymentMethod_Credit card (automatic)  1.560999e+00
2                                 Partner  1.462988e+00
3                              Dependents  1.381598e+00
6                        PaperlessBilling  1.208455e+00
1                           SeniorCitizen  1.153220e+00
0                                  gender  1.002106e+00

c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared
c:\Users\Amir\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared

In [90]:
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score , roc_auc_score
import time

X = df.drop(columns = ['Churn'])
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42 , stratify=y)

THRESHOLD = 0.3

In [92]:
rf_model = RandomForestClassifier(n_estimators=300,
class_weight='balanced',
 random_state=42,
 n_jobs=-1
 )

rf_model.fit(X_train, y_train)

prob = rf_model.predict_proba(X_test)[:, 1]
y_pred = (prob >= THRESHOLD).astype(int)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1035
           1       0.53      0.72      0.61       374

    accuracy                           0.76      1409
   macro avg       0.71      0.74      0.72      1409
weighted avg       0.79      0.76      0.77      1409

In [93]:
prob = rf_model.predict_proba(X_test)[:, 1]


for thresh in [0.25, 0.3, 0.35, 0.40, 0.45, 0.50]:
    y_pred = (prob >= thresh).astype(int)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"Threshold: {thresh:.1f} | Precision: {precision:.4f} | Recall: {recall:.4f} | F1 Score: {f1:.4f}")

Threshold: 0.2 | Precision: 0.4966 | Recall: 0.7861 | F1 Score: 0.6087
Threshold: 0.3 | Precision: 0.5306 | Recall: 0.7193 | F1 Score: 0.6107
Threshold: 0.3 | Precision: 0.5499 | Recall: 0.6631 | F1 Score: 0.6012
Threshold: 0.4 | Precision: 0.5788 | Recall: 0.6283 | F1 Score: 0.6026
Threshold: 0.5 | Precision: 0.6140 | Recall: 0.5615 | F1 Score: 0.5866
Threshold: 0.5 | Precision: 0.6376 | Recall: 0.5080 | F1 Score: 0.5655

In [94]:
lgb_model = lgb.LGBMClassifier(n_estimators=500,
learning_rate=0.05,
class_weight='balanced',
random_state=42,
n_jobs=-1
)


start_time = time.time()
lgb_model.fit(X_train, y_train)
training_time = time.time() - start_time

print(f"Training time: {training_time:.2f} seconds")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1495, number of negative: 4139
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001248 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 637
[LightGBM] [Info] Number of data points in the train set: 5634, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
Training time: 1.16 seconds

In [95]:
start_pred = time.time()
prob = lgb_model.predict_proba(X_test)[:, 1]
y_pred = (prob >= THRESHOLD).astype(int)
pred_time = time.time() - start_pred

print(f"Prediction time: {pred_time:.2f} seconds")

print(classification_report(y_test, y_pred , digits=3))

Prediction time: 0.03 seconds
              precision    recall  f1-score   support

           0      0.914     0.702     0.795      1035
           1      0.498     0.818     0.619       374

    accuracy                          0.733      1409
   macro avg      0.706     0.760     0.707      1409
weighted avg      0.804     0.733     0.748      1409

In [96]:
prob = lgb_model.predict_proba(X_test)[:, 1]

for thresh in [0.25, 0.3, 0.35, 0.40, 0.45, 0.50]:
    y_pred = (prob >= thresh).astype(int)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"Threshold: {thresh:.2f} | Precision: {precision:.4f} | Recall: {recall:.4f} | F1 Score: {f1:.4f}")

Threshold: 0.25 | Precision: 0.4787 | Recall: 0.8422 | F1 Score: 0.6105
Threshold: 0.30 | Precision: 0.4984 | Recall: 0.8182 | F1 Score: 0.6194
Threshold: 0.35 | Precision: 0.5069 | Recall: 0.7861 | F1 Score: 0.6164
Threshold: 0.40 | Precision: 0.5241 | Recall: 0.7567 | F1 Score: 0.6193
Threshold: 0.45 | Precision: 0.5368 | Recall: 0.7406 | F1 Score: 0.6225
Threshold: 0.50 | Precision: 0.5516 | Recall: 0.7005 | F1 Score: 0.6172

In [97]:
from xgboost import XGBClassifier

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
xgb = XGBClassifier(n_estimators=500,
learning_rate=0.05,
max_depth=5,
subsample=0.8,
colsample_bytree=0.8,
random_state=42,
n_jobs=-1,
scale_pos_weight=scale_pos_weight,
eval_metric='logloss'
)
start_time = time.time()
xgb.fit(X_train, y_train)
training_time = time.time() - start_time

print(f"Training time: {training_time:.2f} seconds")

Training time: 1.06 seconds

In [98]:
start_pred = time.time()
prob = lgb_model.predict_proba(X_test)[:, 1]
y_pred = (prob >= THRESHOLD).astype(int)
pred_time = time.time() - start_pred

print(f"Prediction time: {pred_time:.2f} seconds")

print(classification_report(y_test, y_pred , digits=3))

Prediction time: 0.03 seconds
              precision    recall  f1-score   support

           0      0.914     0.702     0.795      1035
           1      0.498     0.818     0.619       374

    accuracy                          0.733      1409
   macro avg      0.706     0.760     0.707      1409
weighted avg      0.804     0.733     0.748      1409

In [99]:
prob = lgb_model.predict_proba(X_test)[:, 1]

for thresh in [0.25, 0.3, 0.35, 0.40, 0.45, 0.50]:
    y_pred = (prob >= thresh).astype(int)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"Threshold: {thresh:.2f} | Precision: {precision:.4f} | Recall: {recall:.4f} | F1 Score: {f1:.4f}")

Threshold: 0.25 | Precision: 0.4787 | Recall: 0.8422 | F1 Score: 0.6105
Threshold: 0.30 | Precision: 0.4984 | Recall: 0.8182 | F1 Score: 0.6194
Threshold: 0.35 | Precision: 0.5069 | Recall: 0.7861 | F1 Score: 0.6164
Threshold: 0.40 | Precision: 0.5241 | Recall: 0.7567 | F1 Score: 0.6193
Threshold: 0.45 | Precision: 0.5368 | Recall: 0.7406 | F1 Score: 0.6225
Threshold: 0.50 | Precision: 0.5516 | Recall: 0.7005 | F1 Score: 0.6172

In [100]:
import optuna

def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 300, 800),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "reg_alpha": trial.suggest_float("reg_alpha", 0, 5),
        "reg_lambda": trial.suggest_float("reg_lambda", 0, 5),
        "random_state": 42,
        "n_jobs": -1,
        "scale_pos_weight": (y_train == 0).sum() / (y_train == 1).sum(),
        "eval_metric": "logloss"
    }
    model = XGBClassifier(**params)
    model.fit(X_train, y_train)
    prob = model.predict_proba(X_test)[:, 1]
    y_pred = (prob >= THRESHOLD).astype(int)
    return recall_score(y_test, y_pred)


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

print("Best hyperparameters:", study.best_params)
print("Best recall score:", study.best_value)

[I 2026-10-26 15:08:11,496] A new study created in memory with name: no-name-203dd588-bb07-4bfd-a64b-ea06306968fa
[I 2026-10-26 15:08:12,250] Trial 0 finished with value: 0.9037433155080213 and parameters: {'n_estimators': 729, 'learning_rate': 0.17136739598381684, 'max_depth': 7, 'subsample': 0.9146604437665132, 'colsample_bytree': 0.5515827541236564, 'min_child_weight': 1, 'gamma': 4.282142669262058, 'reg_alpha': 3.743783925752428, 'reg_lambda': 4.995262637182096}. Best is trial 0 with value: 0.9037433155080213.
[I 2026-10-26 15:08:12,944] Trial 1 finished with value: 0.9037433155080213 and parameters: {'n_estimators': 640, 'learning_rate': 0.07384246597644063, 'max_depth': 8, 'subsample': 0.8899650848479035, 'colsample_bytree': 0.7597787206840838, 'min_child_weight': 3, 'gamma': 3.4024926838325698, 'reg_alpha': 4.563730155317239, 'reg_lambda': 3.7366698211638756}. Best is trial 0 with value: 0.9037433155080213.
[I 2026-10-26 15:08:13,453] Trial 2 finished with value: 0.9010695187165776 and parameters: {'n_estimators': 397, 'learning_rate': 0.08271176984686382, 'max_depth': 3, 'subsample': 0.6075804436463232, 'colsample_bytree': 0.8226377999095282, 'min_child_weight': 9, 'gamma': 3.346701746047593, 'reg_alpha': 3.0824148441444166, 'reg_lambda': 4.791686972807423}. Best is trial 0 with value: 0.9037433155080213.
[I 2026-10-26 15:08:14,108] Trial 3 finished with value: 0.9037433155080213 and parameters: {'n_estimators': 639, 'learning_rate': 0.12960410355721597, 'max_depth': 5, 'subsample': 0.9390881375748721, 'colsample_bytree': 0.5314542389973378, 'min_child_weight': 10, 'gamma': 4.700682266085006, 'reg_alpha': 0.6482620854067817, 'reg_lambda': 2.956722567467912}. Best is trial 0 with value: 0.9037433155080213.
[I 2026-10-26 15:08:15,104] Trial 4 finished with value: 0.9090909090909091 and parameters: {'n_estimators': 717, 'learning_rate': 0.033195204389089336, 'max_depth': 3, 'subsample': 0.7872632067899709, 'colsample_bytree': 0.5560077120652327, 'min_child_weight': 5, 'gamma': 2.306199849337576, 'reg_alpha': 3.596523672489989, 'reg_lambda': 1.8869499493869757}. Best is trial 4 with value: 0.9090909090909091.
[I 2026-10-26 15:08:16,014] Trial 5 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 596, 'learning_rate': 0.010669165692773302, 'max_depth': 3, 'subsample': 0.8706450038025983, 'colsample_bytree': 0.6266900192501874, 'min_child_weight': 1, 'gamma': 4.3362133491639065, 'reg_alpha': 0.1970537703500308, 'reg_lambda': 3.779869259630511}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:17,199] Trial 6 finished with value: 0.8796791443850267 and parameters: {'n_estimators': 457, 'learning_rate': 0.029753785962212495, 'max_depth': 10, 'subsample': 0.7643657159211297, 'colsample_bytree': 0.5695068310581898, 'min_child_weight': 10, 'gamma': 1.771893661446271, 'reg_alpha': 0.501168873126841, 'reg_lambda': 1.6449658594173693}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:18,227] Trial 7 finished with value: 0.8475935828877005 and parameters: {'n_estimators': 380, 'learning_rate': 0.05987977644686532, 'max_depth': 8, 'subsample': 0.5969385528706208, 'colsample_bytree': 0.6183466831005349, 'min_child_weight': 7, 'gamma': 1.4556349540930809, 'reg_alpha': 0.29093577266165904, 'reg_lambda': 3.176087857552256}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:19,026] Trial 8 finished with value: 0.8636363636363636 and parameters: {'n_estimators': 417, 'learning_rate': 0.05148913979038634, 'max_depth': 7, 'subsample': 0.9906584813432732, 'colsample_bytree': 0.9290148567967045, 'min_child_weight': 2, 'gamma': 0.7947150098291211, 'reg_alpha': 0.7036197704469965, 'reg_lambda': 0.2901962760504151}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:19,549] Trial 9 finished with value: 0.8983957219251337 and parameters: {'n_estimators': 360, 'learning_rate': 0.13323778766288166, 'max_depth': 6, 'subsample': 0.9077121640286179, 'colsample_bytree': 0.7687635595450352, 'min_child_weight': 6, 'gamma': 3.4633255827225726, 'reg_alpha': 1.3364128700722666, 'reg_lambda': 0.92466554473426}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:20,504] Trial 10 finished with value: 0.8823529411764706 and parameters: {'n_estimators': 786, 'learning_rate': 0.09066700918580772, 'max_depth': 9, 'subsample': 0.9202519785580117, 'colsample_bytree': 0.5408323870151238, 'min_child_weight': 1, 'gamma': 3.0841935688296997, 'reg_alpha': 0.05586876285048126, 'reg_lambda': 3.8653222822509097}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:21,360] Trial 11 finished with value: 0.9090909090909091 and parameters: {'n_estimators': 638, 'learning_rate': 0.03520919588206319, 'max_depth': 3, 'subsample': 0.9569295271447904, 'colsample_bytree': 0.7567520855018425, 'min_child_weight': 1, 'gamma': 2.370865469911255, 'reg_alpha': 1.2596825315399338, 'reg_lambda': 4.272423530545772}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:22,146] Trial 12 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 680, 'learning_rate': 0.049136094710533415, 'max_depth': 3, 'subsample': 0.8670638172751869, 'colsample_bytree': 0.6817887141678466, 'min_child_weight': 7, 'gamma': 4.710035767539955, 'reg_alpha': 1.7673321548673153, 'reg_lambda': 3.9789647017067127}. Best is trial 5 with value: 0.9197860962566845.
[I 2026-10-26 15:08:22,969] Trial 13 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 612, 'learning_rate': 0.01779809390888113, 'max_depth': 4, 'subsample': 0.9326015138218645, 'colsample_bytree': 0.5508783971536334, 'min_child_weight': 4, 'gamma': 4.935483246626658, 'reg_alpha': 0.6226925570066941, 'reg_lambda': 2.877782000389661}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:24,207] Trial 14 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 583, 'learning_rate': 0.052937264939234875, 'max_depth': 4, 'subsample': 0.9561043330215899, 'colsample_bytree': 0.5164753763374317, 'min_child_weight': 1, 'gamma': 4.911176179319194, 'reg_alpha': 2.071291592995924, 'reg_lambda': 1.6509549662467535}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:24,917] Trial 15 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 534, 'learning_rate': 0.028008626172478752, 'max_depth': 5, 'subsample': 0.9518711676438288, 'colsample_bytree': 0.6211164804773412, 'min_child_weight': 1, 'gamma': 3.2957573451480684, 'reg_alpha': 0.7524641101513162, 'reg_lambda': 1.70221961936207}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:25,709] Trial 16 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 672, 'learning_rate': 0.03936748547958639, 'max_depth': 5, 'subsample': 0.8688154512965441, 'colsample_bytree': 0.696382212838278, 'min_child_weight': 3, 'gamma': 4.8567299037515115, 'reg_alpha': 0.16566824495425636, 'reg_lambda': 2.7367627710495723}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:26,760] Trial 17 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 761, 'learning_rate': 0.010523476004223101, 'max_depth': 3, 'subsample': 0.8167973545769461, 'colsample_bytree': 0.5075774022635401, 'min_child_weight': 5, 'gamma': 3.9578267431272462, 'reg_alpha': 0.2909925512740512, 'reg_lambda': 3.4311357077466025}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:27,591] Trial 18 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 690, 'learning_rate': 0.02381645436683455, 'max_depth': 3, 'subsample': 0.9136366991607432, 'colsample_bytree': 0.5249070335000181, 'min_child_weight': 7, 'gamma': 2.3432208098288454, 'reg_alpha': 0.2640514983153011, 'reg_lambda': 2.8230251154923782}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:28,651] Trial 19 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 797, 'learning_rate': 0.013302574118729983, 'max_depth': 5, 'subsample': 0.9014729984942117, 'colsample_bytree': 0.5147467128985803, 'min_child_weight': 4, 'gamma': 3.9456941481596344, 'reg_alpha': 0.3162540473479737, 'reg_lambda': 4.071593866249369}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:29,464] Trial 20 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 656, 'learning_rate': 0.01712092268279309, 'max_depth': 3, 'subsample': 0.8997002694231242, 'colsample_bytree': 0.5242923066750036, 'min_child_weight': 6, 'gamma': 3.5832926638839018, 'reg_alpha': 1.9044345036194987, 'reg_lambda': 3.645405634417556}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:30,276] Trial 21 finished with value: 0.9090909090909091 and parameters: {'n_estimators': 707, 'learning_rate': 0.04046528869863662, 'max_depth': 4, 'subsample': 0.8337468225261521, 'colsample_bytree': 0.5799598144342131, 'min_child_weight': 5, 'gamma': 3.618929260144693, 'reg_alpha': 0.2669779119690462, 'reg_lambda': 4.650610209905745}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:31,217] Trial 22 finished with value: 0.9144385026737968 and parameters: {'n_estimators': 800, 'learning_rate': 0.025915992352658103, 'max_depth': 4, 'subsample': 0.8336068246402042, 'colsample_bytree': 0.6190422853745958, 'min_child_weight': 7, 'gamma': 4.892922668048733, 'reg_alpha': 0.16471296581786726, 'reg_lambda': 3.54605082246321}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:31,981] Trial 23 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 657, 'learning_rate': 0.022188452736459825, 'max_depth': 4, 'subsample': 0.8934435300693419, 'colsample_bytree': 0.5639647176142177, 'min_child_weight': 3, 'gamma': 4.5925499168923825, 'reg_alpha': 1.3594072899289384, 'reg_lambda': 3.2359819704782775}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:32,886] Trial 24 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 723, 'learning_rate': 0.015451390188745626, 'max_depth': 4, 'subsample': 0.9271325531451954, 'colsample_bytree': 0.6110528109772801, 'min_child_weight': 4, 'gamma': 4.179104195740885, 'reg_alpha': 0.19411137218215924, 'reg_lambda': 1.898545549203051}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:33,779] Trial 25 finished with value: 0.9064171122994652 and parameters: {'n_estimators': 652, 'learning_rate': 0.024298123728759072, 'max_depth': 5, 'subsample': 0.7295948259392532, 'colsample_bytree': 0.5616429956190554, 'min_child_weight': 4, 'gamma': 3.666990201346376, 'reg_alpha': 1.1566715175945959, 'reg_lambda': 2.3610335918169474}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:34,468] Trial 26 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 582, 'learning_rate': 0.028184965942403283, 'max_depth': 3, 'subsample': 0.8216596453772999, 'colsample_bytree': 0.5186362201044923, 'min_child_weight': 6, 'gamma': 4.584784682327905, 'reg_alpha': 0.30881353145115426, 'reg_lambda': 3.0291248978539156}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:35,101] Trial 27 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 522, 'learning_rate': 0.02379108961399383, 'max_depth': 3, 'subsample': 0.9643303745683791, 'colsample_bytree': 0.6616131185914458, 'min_child_weight': 1, 'gamma': 4.180815986439595, 'reg_alpha': 0.19979044019494308, 'reg_lambda': 3.361895912389945}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:35,953] Trial 28 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 638, 'learning_rate': 0.013958069610449625, 'max_depth': 3, 'subsample': 0.8485387850744495, 'colsample_bytree': 0.5517319739121307, 'min_child_weight': 3, 'gamma': 3.9824861256002233, 'reg_alpha': 0.18736573797135647, 'reg_lambda': 2.369550974289494}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:36,856] Trial 29 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 591, 'learning_rate': 0.010683328172005832, 'max_depth': 4, 'subsample': 0.7933972210106569, 'colsample_bytree': 0.6337382806883894, 'min_child_weight': 4, 'gamma': 4.803793219831057, 'reg_alpha': 0.7822464427728071, 'reg_lambda': 3.525856736181156}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:37,618] Trial 30 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 596, 'learning_rate': 0.02070194574676377, 'max_depth': 3, 'subsample': 0.9147565007779981, 'colsample_bytree': 0.5123277992680069, 'min_child_weight': 4, 'gamma': 4.3099806595304795, 'reg_alpha': 0.05943255476522846, 'reg_lambda': 2.7080874190694533}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:38,379] Trial 31 finished with value: 0.9144385026737968 and parameters: {'n_estimators': 656, 'learning_rate': 0.02646337735125285, 'max_depth': 3, 'subsample': 0.8397122820212908, 'colsample_bytree': 0.6109774461619556, 'min_child_weight': 3, 'gamma': 3.9574416330592475, 'reg_alpha': 0.16834509628976185, 'reg_lambda': 1.7646828797399685}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:39,100] Trial 32 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 599, 'learning_rate': 0.01939825576481485, 'max_depth': 3, 'subsample': 0.9171326654373216, 'colsample_bytree': 0.6169391838453949, 'min_child_weight': 1, 'gamma': 4.010508597944558, 'reg_alpha': 0.3572788578349454, 'reg_lambda': 2.1277005888021465}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:39,781] Trial 33 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 550, 'learning_rate': 0.023874144057710427, 'max_depth': 3, 'subsample': 0.9621576607049659, 'colsample_bytree': 0.6391598470602549, 'min_child_weight': 5, 'gamma': 4.285276801815397, 'reg_alpha': 0.1268702784093726, 'reg_lambda': 3.2655302823128727}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:40,579] Trial 34 finished with value: 0.9144385026737968 and parameters: {'n_estimators': 667, 'learning_rate': 0.030279728377327866, 'max_depth': 3, 'subsample': 0.8191061977827487, 'colsample_bytree': 0.536001349511607, 'min_child_weight': 3, 'gamma': 3.8853493924901374, 'reg_alpha': 1.2781707774935054, 'reg_lambda': 2.6908501948829464}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:41,320] Trial 35 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 598, 'learning_rate': 0.04573789049109748, 'max_depth': 3, 'subsample': 0.8953751736178917, 'colsample_bytree': 0.5283073684404621, 'min_child_weight': 4, 'gamma': 4.582715497713685, 'reg_alpha': 0.14593142903337353, 'reg_lambda': 3.669004863005421}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:42,111] Trial 36 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 641, 'learning_rate': 0.015827434694047106, 'max_depth': 3, 'subsample': 0.9078161907603997, 'colsample_bytree': 0.5303936120722099, 'min_child_weight': 6, 'gamma': 4.148096097108758, 'reg_alpha': 0.20189834393258743, 'reg_lambda': 2.204016504107445}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:42,835] Trial 37 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 538, 'learning_rate': 0.018599108894993832, 'max_depth': 4, 'subsample': 0.8517936604571145, 'colsample_bytree': 0.6091770120566409, 'min_child_weight': 5, 'gamma': 4.577122337262694, 'reg_alpha': 0.5406557144012265, 'reg_lambda': 1.5819767439067083}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:43,684] Trial 38 finished with value: 0.9224598930481284 and parameters: {'n_estimators': 626, 'learning_rate': 0.016256361491292032, 'max_depth': 4, 'subsample': 0.9468306819621897, 'colsample_bytree': 0.5570569047802195, 'min_child_weight': 3, 'gamma': 4.163033407985319, 'reg_alpha': 0.8957620971409599, 'reg_lambda': 4.173499905995475}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:44,503] Trial 39 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 646, 'learning_rate': 0.033423629248838474, 'max_depth': 3, 'subsample': 0.722497004080528, 'colsample_bytree': 0.5239381771629102, 'min_child_weight': 6, 'gamma': 3.615832847766593, 'reg_alpha': 0.9016914099525182, 'reg_lambda': 3.586904079095097}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:45,261] Trial 40 finished with value: 0.9117647058823529 and parameters: {'n_estimators': 652, 'learning_rate': 0.03494492425925033, 'max_depth': 4, 'subsample': 0.7917405165692407, 'colsample_bytree': 0.5513539461830075, 'min_child_weight': 3, 'gamma': 4.923034117964559, 'reg_alpha': 0.3934903427778669, 'reg_lambda': 2.619815462364869}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:45,884] Trial 41 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 574, 'learning_rate': 0.055642753341134936, 'max_depth': 3, 'subsample': 0.9170684777994194, 'colsample_bytree': 0.5444524157771715, 'min_child_weight': 4, 'gamma': 4.566610600882226, 'reg_alpha': 0.1935816031251819, 'reg_lambda': 1.9647575480887303}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:46,738] Trial 42 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 787, 'learning_rate': 0.035515752175075535, 'max_depth': 3, 'subsample': 0.8567781000244522, 'colsample_bytree': 0.5588613437625524, 'min_child_weight': 4, 'gamma': 3.7535436219067537, 'reg_alpha': 0.23894414985370235, 'reg_lambda': 2.8476335222258786}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:47,418] Trial 43 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 575, 'learning_rate': 0.030230145577287062, 'max_depth': 3, 'subsample': 0.8190339433000569, 'colsample_bytree': 0.5349714567184091, 'min_child_weight': 3, 'gamma': 4.923575658902572, 'reg_alpha': 0.5543244226149298, 'reg_lambda': 1.9388271387503135}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:48,319] Trial 44 finished with value: 0.9171122994652406 and parameters: {'n_estimators': 615, 'learning_rate': 0.014235299158324582, 'max_depth': 4, 'subsample': 0.8649843846819466, 'colsample_bytree': 0.5555336603690301, 'min_child_weight': 4, 'gamma': 4.077841004158138, 'reg_alpha': 0.22871230588739444, 'reg_lambda': 3.338595184338618}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:49,164] Trial 45 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 629, 'learning_rate': 0.014249824038970108, 'max_depth': 4, 'subsample': 0.9856003531115136, 'colsample_bytree': 0.5577880388959838, 'min_child_weight': 5, 'gamma': 4.539321855798001, 'reg_alpha': 0.35274502911536393, 'reg_lambda': 2.8523046641028404}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:49,871] Trial 46 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 656, 'learning_rate': 0.032865022018952375, 'max_depth': 3, 'subsample': 0.9619999683164678, 'colsample_bytree': 0.5497152114294597, 'min_child_weight': 3, 'gamma': 4.229432983930602, 'reg_alpha': 0.581908588245125, 'reg_lambda': 2.5155933580846597}. Best is trial 13 with value: 0.9224598930481284.
[I 2026-10-26 15:08:50,895] Trial 47 finished with value: 0.9197860962566845 and parameters: {'n_estimators': 758, 'learning_rate': 0.01053956956683674, 'max_depth': 3, 'subsample': 0.8879739255913971, 'colsample_bytree': 0.5360258264785484, 'min_child_weight': 4, 'gamma': 3.701844254943519, 'reg_alpha': 0.06371486935751736, 'reg_lambda': 3.307146455509813}. Best is trial 13 with value: 0.9224598930481284.

Best hyperparameters: {'n_estimators': 612, 'learning_rate': 0.01779809390888113, 'max_depth': 4, 'subsample': 0.9326015138218645, 'colsample_bytree': 0.5508783971536334, 'min_child_weight': 4, 'gamma': 4.935483246626658, 'reg_alpha': 0.6226925570066941, 'reg_lambda': 2.877782000389661}
Best recall score: 0.9224598930481284

In [101]:
sacle_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
best_params = study.best_params
best_params.update({"scale_pos_weight": sacle_pos_weight,
"random_state": 42,
"n_jobs": -1,
"eval_metric": "logloss"
})


xgb_best = XGBClassifier(**best_params)

start_time = time.time()
xgb_best.fit(X_train, y_train)
training_time = time.time() - start_time

print(f"Training time: {training_time:.2f} seconds")

start_pred = time.time()
prob = xgb_best.predict_proba(X_test)[:, 1]
y_pred = (prob >= THRESHOLD).astype(int)
pred_time = time.time() - start_pred

print(f"Prediction time: {pred_time:.2f} seconds")

print(classification_report(y_test, y_pred , digits=3))

Training time: 0.76 seconds
Prediction time: 0.02 seconds
              precision    recall  f1-score   support

           0      0.953     0.569     0.713      1035
           1      0.436     0.922     0.592       374

    accuracy                          0.663      1409
   macro avg      0.695     0.746     0.652      1409
weighted avg      0.816     0.663     0.681      1409

In [106]:
mlflow.end_run()

In [107]:
import mlflow
import mlflow.sklearn
import os


project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
mlflow.set_tracking_uri(f"sqlite:///mlflow.db")
mlflow.set_experiment("Customer_Churn_Prediction")



with mlflow.start_run():
    scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
    best_params = study.best_params

    best_params.update({"scale_pos_weight": scale_pos_weight,
                        "random_state": 42,
                          "n_jobs": -1,
                            "eval_metric": "logloss"
    })

mlflow.log_params(best_params)




start_time = time.time()
xgb = XGBClassifier(**best_params)
xgb.fit(X_train, y_train)
training_time = time.time() - start_time
mlflow.log_metric("training_time", training_time)


start_pred = time.time()
prob = xgb.predict_proba(X_test)[:, 1]
y_pred = (prob >= THRESHOLD).astype(int)
pred_time = time.time() - start_pred
mlflow.log_metric("prediction_time", pred_time)




precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, prob)






mlflow.log_metric("precision" , precision)
mlflow.log_metric("recall" , recall)
mlflow.log_metric("f1" , f1)
mlflow.log_metric("auc" , auc)





mlflow.xgboost.log_model(xgb, "xgb_model")



print(classification_report(y_test, y_pred , digits=3))

2026/10/26 15:16:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

              precision    recall  f1-score   support

           0      0.953     0.569     0.713      1035
           1      0.436     0.922     0.592       374

    accuracy                          0.663      1409
   macro avg      0.695     0.746     0.652      1409
weighted avg      0.816     0.663     0.681      1409